import { makeStyles } from "@mui/styles";

const useStyles = makeStyles((theme) => ({
  headingPrimary: {
    fontFamily: `"Oswald", sans-serif`,
    fontSize: "48px",
    textTransform: "uppercase",
    color: "#5c64ca",
  },
  headingSecondaryField: {
    width: "60%",
    color: "#495057",
  },
  headingSecondary: { textAlign: "center", fontFamily: `"Oswald", sans-serif` },
  todoList: {
    width: "800px",
    height: "400px",
    overflowY: "scroll",
    paddingTop: "20px",
    margin: "20px 0px 25px 0px",
  },
  statusComplete: {
    backgroundColor: "orangered",
    width: "20px",
    height: "40px",
    zIndex: "2",
  },
  contentArea: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0 25px 30px 25px",
    margin: " 35px auto",
    width: "900px",
    height: "auto",
    backgroundColor: "#f1f3f5",
    borderRadius: "10px",
    boxShadow: "rgb(38, 57, 77) 0px 20px 30px -10px",
  },
  completeFieled: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    height: "150px",
    width: "inherit",
  },
  progressField: {
    width: "85%",
    backgroundColor: "#f1f3f5",
    padding: "5px 15px 15px 15px",
    borderRadius: "5px",
  },
  progressText: {
    margin: "0 0 5px 0",
    padding: "0px",
    textAlign: "center",
    color: "#5c64ca",
    fontSize: "18px",
    fontWeight: "500",
    textTransform: "uppercase",
  },
  staticField: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: "5px",
  },
  staticText: { margin: "0px", padding: "0px" },
  staticTextLeft: { color: "#2E7D32", fontWeight: "500" },
  staticTextMiddle: { color: "#5c64ca", fontWeight: "500" },
  staticTextRight: { color: "#1A90FF", fontWeight: "500" },
  todo: { marginBottom: "1px" },
  btnActions: {
    display: "flex",
    alignItems: "center",
  },
  deleteBtn: {
    marginLeft: "auto",
    marginRight: "5px",
  },
  completeText: {
    padding: "0px",
    margin: "0px",
    fontWeight: "500",
    width: "85px",
  },
  alarmDate: { display: "flex", alignItems: "center" },
  iconClock: { marginRight: "3px", marginLeft: "20px" },
  inputField: {
    display: "flex",
    justifyContent: "space-between",
    columnGap: "35px",
    marginTop: "30px",
    marginLeft: "20px",
    marginRight: "20px",
  },
  inputsField: { width: "200px" },
  inputsEditFields: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    margin: "auto",
    width: "350px",
    height: "280px",
  },
  inputsEdit: {
    width: "310px",
    height: "55px",
    marginBottom: "20px",
  },
  inputsEditDate: {
    width: "200px",
    height: "55px",
  },
  inputDateAndEditButton: {
    display: "flex",
    alignItems: "center",
    columnGap: "30px",
  },
  checkboxModalField: {
    display: "flex",
    alignItems: "center",
    marginTop: "5px",
  },
  checkboxModalText: { color: "#1A90FF", fontSize: "18px", fontWeight: "500" },
}));

export default useStyles;
